### ISSUE TITLE
Characters Not Aligned

### ISSUE THREAD

**Issue by Nixpower** [bus1/displayotron#1]
Hi, I'm using a Displayotron 3000 on a Raspberry Pi 3 and I'm having some difficulty having the text characters align properly, as when I run the sample "Hello World" script, the display cuts off some characters and displays "llo World". Changing the script to print "  Hello World" makes it work. However, the alignment issues are different for different sets of characters, as some will only be off by 1 character while others will be offset by 2 or 3.

Thanks,
Nixpower

**Comment by kaysievers** [comment]
This repository is a toy project, a driver written in C. There is no "hello world", so I assume you intended to report against the official product, not this repository, right?

I should probably change the name of this repository, i just liked the name so much. :)

**Comment by Nixpower** [comment]
Oh, sorry, this is completely my fault, thanks anyways!
